# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-03-25 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_certs_exptime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certs',
            name='alarm',
        ),
        migrations.AddField(
            model_name='certs',
            name='beian',
            field=models.BooleanField(default=False, verbose_name='有无备案'),
        ),
        migrations.AddField(
            model_name='certs',
            name='qqwaf',
            field=models.BooleanField(default=False, verbose_name='是否被QQ拦截'),
        ),
        migrations.AddField(
            model_name='certs',
            name='waf',
            field=models.BooleanField(default=False, verbose_name='是否被墙'),
        ),
        migrations.AddField(
            model_name='certs',
            name='wxwaf',
            field=models.BooleanField(default=False, verbose_name='是否被微信拦截'),
        ),
    ]
