# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-03-25 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_certs_qqwaf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certs',
            name='issued_by',
        ),
        migrations.AddField(
            model_name='certs',
            name='a_notes',
            field=models.CharField(default=django.utils.timezone.now, max_length=45, verbose_name='域名A记录'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certs',
            name='dtype',
            field=models.IntegerField(blank=True, default=4, null=True, verbose_name='域名类型'),
        ),
    ]
