# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-03-25 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200325_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certs',
            name='dtype',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='域名类型'),
        ),
    ]
