from django.conf.urls import url

from app import views

urlpatterns = [
    # url(r'^/', views.login, name='login'),
    url(r'^login/', views.login, name='login'),
    url(r'^logout/', views.user_logout, name='logout'),
    url(r'^domaininfo/', views.domain_info, name='domain_info'),
    url(r'^adddomain/', views.add_domain, name='adddomain'),
    url(r'^search/', views.search, name='search'),
    url(r'^delete/', views.delete_date, name='delete'),
    url(r'^palcesort/', views.place_sort, name='place_sort'),
    url(r'^typesort/', views.type_sort, name='type_sort'),
    url(r'^label/', views.label_data, name='label'),
    url(r'^sort291/', views.sort_291, name='sort_291'),
    url(r'^sort646/', views.sort_646, name='sort_646'),
    url(r'^sortjj/', views.sort_jj, name='sort_jj'),
    url(r'^sortty1/', views.sort_ty1, name='sort_ty1'),
    url(r'^sortty2/', views.sort_ty2, name='sort_ty2'),
    url(r'^sorttc/', views.sort_tc, name='sort_tc'),
    url(r'^sorttcgj/', views.sort_tcgj, name='sort_tcgj'),
    url(r'^sorttcss/', views.sort_tcss, name='sort_tcss'),
    url(r'^sortycgj/', views.sort_ycgj, name='sort_ycgj'),
    url(r'^sortscgj/', views.sort_scgj, name='sort_scgj'),
    url(r'^sortqcgj/', views.sort_qcgj, name='sort_qcgj'),
    url(r'^sortmcgj/', views.sort_mcgj, name='sort_mcgj'),
    url(r'^sorttc6/', views.sort_tc6, name='sort_tc6'),
    url(r'^sortmd/', views.sort_master_domain, name='sort_master_domain'),
    url(r'^sortldy/', views.sort_ldy, name='sort_ldy'),
    url(r'^sortqd/', views.sort_qd, name='sort_qd'),
    url(r'^labeldreamin/', views.label_dreamin, name='label_dreamin'),
    url(r'^labelremain/', views.label_remain, name='label_remain'),
    url(r'^labelwxwaf/', views.label_wxwaf, name='label_wxwaf'),
    url(r'^labelwaf/', views.label_waf, name='label_waf'),
    url(r'^labelbeian/', views.label_beian, name='label_beian'),
    url(r'^update/', views.update, name='update'),
    url(r'^addinbulk/', views.add_in_bulk, name='add_in_bulk'),
]
